version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-go
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  redis:
    image: redis:latest
    container_name: redis-go
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data/db
